# UTS-3 My Stories for You

Leadership Skills: Saya berencana membawa ilmu leadership yang sudah saya pelajari untuk memudahkan, mengembangkan dan mengorganisir cara saya untuk berdiskusi, berkolaborasi, membuat keputusan, dan memimpin sebuah tim. Contohnya dalam proyek sosial, saya akan berusaha untuk membuat diskusi dalam tim lebih terbuka dan menarik, sehingga kami bisa mengumpulkan ide dengan lebih efektif. Saya juga akan  Saya juga akan lebih mempelajari dan memahami tentang kepribadian seseorang sebelum saya mulai bekerja sama dalam sebuah proyek penelitian, maupun tugas sehari-hari di sekolah.

Academic Skills & Development: Pertama-tama, saya akan mengajari teman saya terutama tentang design thinking dan visual communication karena beberapa dari mereka banyak memiliki minat di bidang tersebut. Saya juga akan mengaplikasikannya dalam kehidupan saya sendiri seperti membuat presentasi dalam tugas sekolah sehari-hari, dan juga membuat poster/produk saya dalam proyek sosial lebih menarik. Untuk International and Global Studies, itu sangat membantu saya dalam memahami sesuatu dari berbagai pandangan yang berbeda.

Cultural Immersion: Saya akan mengaplikasikan berbagai hal yang saya dapat dalam cultural immersion terutama tentang punctuality. Tentang bagaimana kita dapat lebih menghargai suatu waktu, janji, atau jadwal kita sendiri. Tidak hanya untuk diri saya sendiri, saya juga akan mengajak teman-teman dan keluarga saya untuk lebih menghargai waktu. Satu hal lagi yang menurut saya sangat penting untuk diaplikasikan di Indonesia yaitu kebiasaan menggunakan transportasi publik dan bagaimana orang Australia mengutamakan para pejalan kaki. Saya akan menghimbau orang disekitar saya untuk lebih sering menggunakan public transport dan lebih menghargai para pejalan kaki.