# UTS-2 My Songs for You

## My Way by Frank Sinatra

“My Way” bercerita tentang seseorang yang menengok kembali perjalanan hidupnya dengan ketenangan dan rasa bangga, karena ia telah menjalani semuanya dengan caranya sendiri. Baris ikoniknya: “I did it my way” adalah deklarasi kebebasan dan integritas pribadi — bahwa meskipun hidup penuh kesalahan dan tantangan, keputusan yang diambil tetap milik diri sendiri.

Hidup bukan tentang hasil sempurna, tapi tentang otonomi dan keberanian untuk memilih jalan sendiri. “My way” bukan sekadar ego, melainkan simbol keutuhan diri, menerima konsekuensi, tidak menyesal, dan tetap setia pada nilai pribadi. “Regrets, I’ve had a few, but then again, too few to mention.” menunjukkan kedewasaan emosional. Seseorang yang sadar akan kekeliruannya, tapi tidak membiarkan itu merusak kebanggaannya atas hidup yang dijalani.

“My Way” bukan tentang kesempurnaan, melainkan tentang ketulusan menjalani hidup sesuai hati, meski dunia mungkin tak selalu mengerti.

{{< video https://youtu.be/qQzdAsjWGPg?si=iT4lCy1wFuhTYVVK>}}

### Lirik
> **[Verse 1]**  
> And now, the end is near  
> And so I face the final curtain  
> My friend, I'll say it clear  
> I'll state my case, of which I'm certain  
> I've lived a life that's full  
> I traveled each and every highway  
> And more, much more than this  
> I did it my way  
> 
> **[Verse 2]**  
> Regrets, I've had a few  
> But then again, too few to mention  
> I did what I had to do  
> And saw it through without exemption  
> I planned each charted course  
> Each careful step along the byway  
> And more, much more than this  
> I did it my way  
> 
> **[Chorus]**  
> Yes, there were times, I'm sure you knew  
> When I bit off more than I could chew  
> But through it all, when there was doubt  
> I ate it up and spit it out  
> I faced it all, and I stood tall  
> And did it my way  
> 
> **[Verse 3]**  
> I've loved, I've laughed and cried  
> I've had my fill, my share of losing  
> And now, as tears subside  
> I find it all so amusing  
> To think I did all that  
> And may I say, not in a shy way  
> Oh, no, oh, no, not me  
> I did it my way  
> 
> **[Chorus]**  
> For what is a man, what has he got?  
> If not himself, then he has naught  
> To say the things he truly feels  
> And not the words of one who kneels  
> The record shows I took the blows  
> And did it my way  
> 
> **[Outro]**  
> Yes, it was my way  

## Memories by Otsuki Maki

“Memories” mengajarkan bahwa kenangan bukan akhir dari kisah, melainkan jejak lembut yang mengingatkan kita betapa berharganya waktu dan orang-orang yang pernah kita miliki.

{{< video https://youtu.be/cWWjANOisLo?si=14Lzob7R37nK3rvf>}}

### Lirik
> **[Verse 1]**   
> Chisana koro ni wa takara no chizu ga  
> Atama no naka ni ukandeite  
> Itsudemo sagashita kiseki no basho o  
> Shiranai dareka ni makenai you ni  
> 
> **[Pre-Chorus]**  
> (La, la, la, la)  
> Ima de wa  
> (La, la, la, la)  
> Hokori darake no mainichiItsu no hi ka  
> (La, la, la, la)  
> Subete no  
> (La, la, la, la)  
> Toki ni mi o makaseru dake      
> 
> **[Chorus]**  
> Moshi mo sekai ga kawaru no nara  
> Nanimo shiranai koro no watashi ni  
> Tsurete itte omoide ga  
> Iro asenai you ni  
> 
> **[Verse 2]**  
> Chisana koro kara uta o utatte  
> Yume miru kokoro atatameteta  
> Minna de maneshita himitsu no merodei  
> Kondo wa jouzu ni kikoeru you ni  
> 
> **[Pre-Chorus]**  
> (La, la, la, la)  
> Ima de wa  
> (La, la, la, la)  
> Tame iki tsuite bakari de  
> Daremo mada  
> (La, la, la, la)  
> Hontou no  
> (La, la, la, la)  
> Yume sae tsukamenai mama  
> 
> **[Chorus]**  
> Moshi mo jidai ga modoru no nara  
> Namida o shitta koro no watashi ni  
> Tsurete itte setsunasa ga  
> Oitsukanai you ni  
> Moshi mo sekai ga kawaru no nara  
> Nanimo shiranai koro no watashi ni  
> Tsurete itte omoide ga  
> Iro asenai you ni      
> 
> **[Outro]**  
> Tsurete itte setsunasa ga  
> Oitsukanai you ni  

## Voices (Entrance Theme - Randy Rorton) [feat. Rev Theory]

Lagu ini memiliki pesan bahwa setiap orang memiliki sisi gelap atau insting liar di dalam dirinya, dan itu tidak selalu buruk. Yang terpenting adalah bagaimana kita mengontrol sisi itu agar menjadi sumber kekuatan, bukan kehancuran.

“Voices” mengajarkan kita untuk berdamai dengan diri sendiri, bahkan dengan bagian-bagian yang sulit diterima, karena dari situlah lahir ketegasan, keberanian, dan kendali sejati atas hidup kita.

{{< video https://youtu.be/pM76LtznNrc?si=deuvjeb8yc6Dcy2E>}}

### Lirik
> **[Intro]**  
> I hear voices in my head  
> They counsel me  
> They understand  
> They talk to me  
> 
> **[Verse 1]**
> You got your rules and your religion  
> All designed to keep you safe  
> But when rules start getting broken  
> You start questioning your faith  
> I have a voice that is my savior  
> Hates to love and loves to hate  
> I have a voice that has the knowledge  
> And the power to rule your fate  
> 
> **[Pre-Chorus]**  
> I hear voices cryin'  
> I see heroes dyin'  
> I taste blood that's dryin'  
> I feel tension risin'  
> 
> **[Chorus]**  
> I hear voices in my head  
> They counsel me, they understand  
> They talk to me, they talk to me (Oh!)  
> They tell me things that I will do  
> They show me things I'll do to you  
> They talk to me (Talk to me, talk to me, talk to me!)  
> They talk to me (Talk to me, talk to me, talk to me!)  
> 
> **[Verse 2]**  
> All the lawyers are defenseless  
> All the doctors are disease  
> And the preachers all are sinners  
> And the police just take the grease  
> All you judges, you are guilty  
> All the bosses I will fire  
> All you bankers will have losses  
> Politicians all are liars  
> 
> **[Bridge]**  
> I see darkness fallin'  
> I hear voices callin'  
> I feel justice crawlin'  
> I see faith has fallen  
> 
> **[Chorus]**  
> I hear voices in my head  
> They counsel me, they understand  
> They talk to me, they talk to me (Oh, oh, oh!)  
> They tell me things that I will do  
> They show me things I'll do to you  
> They talk to me (Talk to me, talk to me, talk to me!)  
> 
> **[Guitar Solo]**  
> 
> [Pre-Chorus]  
> I hear voices cryin'  
> I see heroes dyin'  
> I taste blood that's dryin'  
> I feel tension risin'  
> 
> **[Chorus]**  
> I hear voices in my head  
> They counsel me, they understand  
> They talk to me, they talk to me (Oh, oh, oh!)  
> They tell me things that I will do  
> They show me things I'll do to you  
> They talk to me (Talk to me, talk to me, talk to me!)  
> They talk to me (Talk to me, talk to me, talk to me!)  